In [1]:
# Only for colab
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [2]:
import os, shutil
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import optimizers
from tensorflow.keras import preprocessing
import os, shutil, glob
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image

## Load data
### Make sure this file and original dataset in the same directory

In [4]:
# Directory in which we store our dataset

# Old dataset path
original_dataset_dir =  'drive/My Drive/lung/filtered'

# New dataset path
base_dir = 'drive/My Drive/lung/new_set'
# Create a new directory

# New dataset path
test_dir = 'drive/My Drive/lung/encoded'

#os.mkdir(base_dir)   # comment this line it if you've run it


In [5]:
# Directory in which we store training, validation
# And Create directories of training and validation for normal and pneumonia respectively 

train_dir = os.path.join(base_dir,'train')
#os.mkdir(train_dir)               # comment this line it if you've run it

validation_dir = os.path.join(base_dir,'validation')
#os.mkdir(validation_dir)          # comment this line it if you've run it


train_normal_dir = os.path.join(train_dir, 'NORMAL')
#os.mkdir(train_normal_dir)        # comment this line it if you've run it

train_pneumonia_dir = os.path.join(train_dir, 'PNEUMONIA')
#os.mkdir(train_pneumonia_dir)     # comment this line it if you've run it

validation_normal_dir = os.path.join(validation_dir, 'NORMAL')
#os.mkdir(validation_normal_dir)   # ccomment this line it if you've run it

validation_pneumonia_dir = os.path.join(validation_dir, 'PNEUMONIA')
#os.mkdir(validation_pneumonia_dir)# comment this line it if you've run it

test_normal_dir = os.path.join(test_dir, 'NORMAL')
#os.mkdir(validation_normal_dir)   # ccomment this line it if you've run it

test_pneumonia_dir = os.path.join(test_dir, 'PNEUMONIA')
#os.mkdir(validation_pneumonia_dir)# comment this line it if you've run it

print(train_dir)

drive/My Drive/lung/new_set/train


In [6]:
# All jpeg data from old directory
imageList_normal = glob.glob(os.path.join( (original_dataset_dir + '/NORMAL/'), '*.jpeg'))
imageList_pneumonia = glob.glob(os.path.join( (original_dataset_dir + '/PNEUMONIA/'), '*.jpeg'))

# All jpeg data from new directories
imageList_train_normal = glob.glob(os.path.join( (base_dir + '/train/NORMAL/'), '*.jpeg'))
imageList_val_normal = glob.glob(os.path.join( (base_dir + '/validation/NORMAL/'), '*.jpeg'))

imageList_train_pneumonia = glob.glob(os.path.join(  (base_dir + '/train/PNEUMONIA/'), '*.jpeg'))
imageList_val_pneumonia = glob.glob(os.path.join(  (base_dir + '/validation/PNEUMONIA/'), '*.jpeg'))

imageList_test_normal = glob.glob(os.path.join( './encoded/NORMAL/', '.txt'))
imageList_test_pneumonia  = glob.glob(os.path.join( './encoded/PNEUMONIA/', '.txt'))


In [73]:
def is_file(fname_from,imageList):
    check=False
    for f in imageList: 
        fname_to = os.path.basename(f)
        if(fname_to == fname_from):
            check=True
    return check

In [7]:
# \\don't run this again// 
normal_cases_dir =   (original_dataset_dir + '/NORMAL/')    # Old normal path
pneumonia_cases_dir = (original_dataset_dir + '/PNEUMONIA/')# Old pneumonia path


LENTH_DATASET=len(imageList_normal)                # total normal images (as the same as pneumonia images)

split_train_percent=int(LENTH_DATASET*0.8)   #0.8 for train data
split_val_percent=int(LENTH_DATASET-split_train_percent)  #0.2 for train data

count=0

# Split normal data into 80% train and 20% validation
for f in imageList_normal:
    count+=1    
    fname = os.path.basename(f)
    if(count<=split_train_percent and is_file(fname,imageList_train_normal)==False):
        src = os.path.join(normal_cases_dir, fname)
        dst = os.path.join(train_normal_dir, fname)
        shutil.copyfile(src, dst)
    elif(count>split_train_percent and is_file(fname,imageList_val_normal)==False):
        src = os.path.join(normal_cases_dir, fname)
        dst = os.path.join(validation_normal_dir, fname)
        shutil.copyfile(src, dst)
    
count=0

# Split pneumonia data into 80% train and 20% validation
for f in imageList_pneumonia:
    count+=1    
    fname = os.path.basename(f)
    if(count<=split_train_percent and is_file(fname,imageList_train_pneumonia)==False):
        src = os.path. join(pneumonia_cases_dir, fname)
        dst = os.path.join(train_pneumonia_dir, fname)
        shutil.copyfile(src, dst)
    elif(count>split_train_percent and is_file(fname,imageList_val_pneumonia)==False):
        src = os.path.join(pneumonia_cases_dir, fname)
        dst = os.path.join(validation_pneumonia_dir, fname)
        shutil.copyfile(src, dst)
        

In [7]:
print('total training normal images:', len(os.listdir(train_normal_dir)))
print('total training pneumonia images:', len(os.listdir(train_pneumonia_dir)))

print('total validation normal images:', len(os.listdir(validation_normal_dir)))
print('total validation pneumonia images:', len(os.listdir(validation_pneumonia_dir)))

total training normal images: 1072
total training pneumonia images: 1072
total validation normal images: 269
total validation pneumonia images: 269


In [ ]:
# Structure of directory

BRANCH = '├─'
LAST_BRANCH = '└─'
TAB = '│  '
EMPTY_TAB = '   '


def get_dir_list(path, placeholder=''):
    folder_list = [folder for folder in os.listdir(path) if os.path.isdir(os.path.join(path, folder))]
    file_list = [file for file in os.listdir(path) if os.path.isfile(os.path.join(path, file))]
    result = ''
    for folder in folder_list[:-1]:
        result += placeholder + BRANCH + folder + '\n'
        result += get_dir_list(os.path.join(path, folder), placeholder + TAB)
    if folder_list:
        result += placeholder + (BRANCH if file_list else LAST_BRANCH) + folder_list[-1] + '\n'
        result += get_dir_list(os.path.join(path, folder_list[-1]), placeholder + (TAB if file_list else EMPTY_TAB))
    return result
if __name__ == '__main__':
    print(get_dir_list('./new_set'))

## Data visualization

In [ ]:
from glob import glob
import cv2
print("No Pneumonia")
multipleImages = glob('./new_set/train/NORMAL/**')
i_ = 0
plt.rcParams['figure.figsize'] = (10.0, 10.0)
plt.subplots_adjust(wspace=0, hspace=0)
for l in multipleImages[:10]:
    im = cv2.imread(l)
    im = cv2.resize(im, (128, 128)) 
    plt.subplot(5, 5, i_+1) 
    plt.imshow(cv2.cvtColor(im, cv2.COLOR_BGR2RGB)); plt.axis('off')
    i_ += 1

In [ ]:
print("Pneumonia")
multipleImages = glob('./new_set/train/PNEUMONIA/**')
i_ = 0
plt.rcParams['figure.figsize'] = (10.0, 10.0)
plt.subplots_adjust(wspace=0, hspace=0)
for l in multipleImages[:10]:
    im = cv2.imread(l)
    im = cv2.resize(im, (128, 128)) 
    plt.subplot(5, 5, i_+1) 
    plt.imshow(cv2.cvtColor(im, cv2.COLOR_BGR2RGB)); plt.axis('off')
    i_ += 1

## DataGenerator and Image augmentation

In [10]:
!pip install nbimporter

In [11]:
import nbimporter   # install it for load ipyb inJupyter
#from my_dataGenerator import DataGenerator  # invoke custom data generator class
import numpy as np
import tensorflow as tf
import cv2
from tensorflow.keras.models import Sequential
import math

In [15]:
import math
f = open('/content/drive/MyDrive/lung/encoded/NORMAL/_0_793163.txt')
#np.fromfile(f)
x = np.loadtxt(f)
x = x.astype(int)
x.reshape(224,224,1) 
print (x)

[[ 39  39  48 ...  49  74 103]
 [ 41  38  44 ...  53  72 102]
 [ 39  39  43 ...  50  68 104]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [204]:
class DataGenerator(tf.keras.utils.Sequence):
    'Generates data for Keras'
    def __init__(self, list_IDs, labels, batch_size=32, dim=(224,224), n_channels=1,
                 n_classes=2, shuffle=True,color_mode='grayscale', flag = False):
        'Initialization'
        self.dim = dim
        self.batch_size = batch_size
        self.labels = labels
        self.list_IDs = list_IDs
        self.n_channels = n_channels
        self.n_classes = n_classes
        self.shuffle = shuffle
        self.color_mode=color_mode,
        self.on_epoch_end(),
        self.flag = flag

    def __len__(self):
        'Denotes the number of batches per epoch'
        return int(np.floor(len(self.list_IDs) / self.batch_size))

    def __getitem__(self, index):
        'Generate one batch of data'
        # Generate indexes of the batch
        indexes = self.indexes[index*self.batch_size:(index+1)*self.batch_size]

        # Find list of IDs
        list_IDs_temp = [self.list_IDs[k] for k in indexes]

        # Generate data
        X, y = self.__data_generation(list_IDs_temp)

        return X, y

    def on_epoch_end(self):
        'Updates indexes after each epoch'
        self.indexes = np.arange(len(self.list_IDs))
        if self.shuffle == True:
            np.random.shuffle(self.indexes)

    def __data_generation(self, list_IDs_temp):
        'Generates data containing batch_size samples' # X : (n_samples, *dim, n_channels)
        # Initialization
        X = np.empty((self.batch_size, *self.dim, self.n_channels))
        y = np.empty((self.batch_size), dtype=int)

        # Generate data
        for i, ID in enumerate(list_IDs_temp):
            # Store sample
            X[i,] = self._load_grayscale_image(ID)
            
            # Store class
            y[i] = self.labels[ID]

        return X,y 

    def _load_grayscale_image(self, image_path):
        """Load grayscale image

        :param image_path: path to image to load
        :return: loaded image
        """
        if self.flag:
          img = np.loadtxt(image_path)
          img = img.astype(int)
          img = img.reshape(224,224,1)

        else:
          img = cv2.imread(image_path)
          img = cv2.resize(img, (224,224))
          img = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
          img = img.astype('float')
          img = img.reshape(224,224,1) 
          img = img / 255

        return img

In [205]:
train_0=imageList_train_normal+imageList_val_normal   # all normal images path
lable_train_0=[]
    
lable_train_0 = dict.fromkeys(train_0, 0)             # set normal as 0


train_1=imageList_train_pneumonia+imageList_val_pneumonia  # all pneumonia  images path
lable_train_1=[]
   
lable_train_1 = dict.fromkeys(train_1, 1)      # set pneumonia as 1

lables = {**lable_train_0, **lable_train_1}    # Store both labels into a dictionary 

test_0=imageList_test_normal           # all test images path
lable_test_0=[]

lable_test_0 = dict.fromkeys(test_0, 0)             # set normal as 0

test_1=imageList_test_pneumonia
lable_test_1=[]

lable_test_1 = dict.fromkeys(test_1, 1)      # set pneumonia as 1

test_lables = {**lable_test_0, **lable_test_1}

# lables format as {'./new_set/train/NORMAL\\IM-0115-0001.jpeg': 0, './new_set/train/NORMAL\\NORMAL2-IM-0533-0001.jpeg': 1, ...}


from collections import defaultdict  # install it for easy operate dictionary array

train_d=imageList_train_normal+imageList_train_pneumonia       # all train images path
val_d=imageList_val_normal+imageList_val_pneumonia             # all val images path

test_d=imageList_test_normal+imageList_test_pneumonia          # all test_d images path

partition = defaultdict(list)         #init a dictionary
for j in train_d:
    partition['train'].append(j)      # Train as key and all train images path as value
for j in val_d:
    partition['validation'].append(j) # validation as key and all val images path as value
for j in test_d:
    partition['test'].append(j)       # test as key and all val images path as value
    
#  partition format as  {'train': ['./new_set/train/NORMAL\\IM-0115-0001.jpeg', ..], 
# 'validation': ['./new_set/train/NORMAL\\NORMAL2-IM-0533-0001.jpeg']}

In [206]:
# Parameters
params = {'dim': (224,224),
          'batch_size': 32,
          'n_classes': 2,
          'n_channels': 1,
          'shuffle': True}

# Datasets
partition = partition   # path as IDs
labels = lables         # Labels

# Call DataGenerator function from custom class 
training_generator = DataGenerator(partition['train'], labels, **params)
validation_generator = DataGenerator(partition['validation'], labels, **params)
test_generator = DataGenerator(partition['test'], test_lables, **params, flag=True)

In [16]:
image_width = 224
image_height = 224
batch=32
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=40,
    width_shift_range=0.3,
    height_shift_range=0.3,
    shear_range=0.3,
    zoom_range=0.3,
    horizontal_flip=True,fill_mode = 'nearest',
    
    #channel_shift_range=13,data_format='channels_last',
)
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(image_width, image_height),
    batch_size=batch,
    color_mode='grayscale',     # Channel 3 to channel 1
    class_mode='binary',
)

val_generator = test_datagen.flow_from_directory(
    validation_dir,
    target_size=(image_width, image_height),
    batch_size=batch,          # Channel 3 to channel 1
     color_mode='grayscale',
    class_mode='binary'
)

all_generator = train_datagen.flow_from_directory(
    original_dataset_dir,
    target_size=(image_width, image_height),
    batch_size=batch,          # Channel 3 to channel 1
     color_mode='grayscale',
    class_mode='binary'
)

Found 2144 images belonging to 2 classes.
Found 538 images belonging to 2 classes.
Found 2682 images belonging to 2 classes.


# Custom Layers



In [17]:
from math import ceil
from keras.utils import conv_utils
from tensorflow.keras.layers import *
import tensorflow as tf
from tensorflow.keras import activations
from keras import backend as K
import keras.backend as K
from keras import activations
from tensorflow.python.distribute.sharded_variable import ShardedVariable
from tensorflow.python.ops.variables import PartitionedVariable
from typing import Any, Union, Tuple

In [18]:
@tf.keras.utils.register_keras_serializable()
class MaxPooling(Layer):
    def __init__(self, pool_size=(2, 2), strides=None, padding='VALID', **kwargs):
        super(MaxPooling, self).__init__(**kwargs)
        self.pool_size = pool_size
        if strides is not None:
            self.strides = strides
        else:
            self.strides = pool_size
        self.padding = padding

    def build(self, input_shape):
        super(MaxPooling, self).build(input_shape)

    def call(self, x, **kwargs):
        y = tf.nn.max_pool2d(x, self.pool_size, self.strides, self.padding)
        return y

    def compute_output_shape(self, input_shape):
        rows = ceil(float(input_shape[1]) / float(self.strides[0]))
        cols = ceil(float(input_shape[2]) / float(self.strides[1]))
        return input_shape[0], rows, cols, input_shape[-1]

    #def get_config(self):
    #    config = {'pool_size': self.pool_size,
    #              'padding': self.padding,
    #              'strides': self.strideStride,}
    #             # 'data_format': self.data_format}

    #    base_config = super(MaxPooling, self).get_config()
    #    return dict(list(base_config.items()) + list(config.items()))


    def get_config(self):
        config = super().get_config()
        config.update({
            'pool_size': self.pool_size,
            "strides": self.strides,
            "padding": self.padding,
        })
        return config


In [19]:
@tf.keras.utils.register_keras_serializable()
class Dense(Layer):
    def __init__(self, units=32, activation='relu', **kwargs):
        super(Dense, self).__init__(**kwargs)
        self.units = units
        self.b = None  # b is initialized in build
        self.w = None  # w is initialized in build
        if activation is not None:
            self.activation = activations.get(activation)
        else:
            self.activation = None

    def build(self, input_shape):
        self.b = self.add_weight(
            shape=(self.units,),
            initializer=tf.keras.initializers.zeros(),
            trainable=True,
            dtype='float32',
            name='dense_bias',
        )
        self.w = self.add_weight(
            shape=(input_shape[-1], self.units),
            trainable=True,
            initializer=tf.keras.initializers.random_normal(),
            dtype='float32',
            name="dense_weights",
        )
        super(Dense, self).build(input_shape)

    def call(self, x, **kwargs):
        y = K.dot(x, self.w) + self.b
        if self.activation is not None:
            y = self.activation(y)
        return y

    def compute_output_shape(self, input_shape):
        return input_shape[0], self.units

    def get_config(self):
        config = super().get_config()
        config.update({
            'units': self.units,
            "activation": self.activation,
        })
        return config

In [20]:
@tf.keras.utils.register_keras_serializable()
class Conv2D(Layer):
    bias: Union[Union[PartitionedVariable, ShardedVariable, Conv2D], Any]
    kernel: Union[Union[PartitionedVariable, ShardedVariable, Conv2D], Any]

    def __init__(self, filters: int = 32, kernel_size: Tuple[int, int] = (3, 3), strides: Tuple[int, int] = (1, 1),
                 padding: bool = 'VALID',
                 activation='relu',
                 dilation_rate=(1, 1), batch_size=1, **kwargs):

        self.filters = filters
        self.bias = None
        self.kernel_size = kernel_size
        self.kernel = None
        self.strides = strides
        self.padding = padding
        if activation is not None:
            self.activation = activations.get(activation)
        else:
            self.activation = None
        self.dilation_rate = dilation_rate
        self.batch_size = batch_size
        if K.image_data_format() == 'channels_first':
            self.channel_axis = 0
        else:
            self.channel_axis = -1
        super(Conv2D, self).__init__(**kwargs)

    def build(self, input_shape):
        shape = (self.kernel_size[0], self.kernel_size[1], (input_shape[self.channel_axis]), self.filters)
        self.bias = self.add_weight(name='conv_bias',
                                    shape=(self.filters,),
                                    dtype='float32',
                                    initializer=tf.zeros_initializer(),
                                    trainable=True)
        self.kernel = self.add_weight(name='kernel',
                                      shape=shape,
                                      initializer=tf.keras.initializers.GlorotUniform(),
                                      trainable=True)
        super(Conv2D, self).build(input_shape)

    def call(self, x, **kwargs):
        y = tf.keras.backend.conv2d(x, self.kernel)
        y = K.bias_add(y, self.bias)
        if self.activation is not None:
            y = self.activation(y)
        return y

    def compute_output_shape(self, input_shape):
        batch_size = input_shape[0]
        convX = conv_utils.conv_output_length(
            input_shape[1],
            self.kernel_size[0],
            padding=self.padding,
            stride=self.strides[0],
            dilation=self.dilation_rate[0]
        )
        convY = conv_utils.conv_output_length(
            input_shape[2],
            self.kernel_size[1],
            padding=self.padding,
            stride=self.strides[1],
            dilation=self.dilation_rate[1]
        )
        return batch_size, convX, convY, self.filters

    def get_config(self):
        config = super().get_config()
        config.update({
            "filters": self.filters,
            "kernel_size": self.kernel_size,
            "strides": self.strides,
            "padding": self.padding,
            "activation": self.activation,
            "dilation_rate": self.dilation_rate,
            "batch_size": self.batch_size,
        })
        return config


# MODEL

In [21]:
import keras
from keras.preprocessing.image import ImageDataGenerator
from tensorflow import keras
from keras import layers
import numpy as np
import matplotlib.pyplot as plt
from keras.layers import Input, Dropout, SpatialDropout2D, experimental

model = keras.Sequential([

    keras.layers.Input(shape=(image_width, image_height, 1)),
    Conv2D(filters = 64, padding="zero", strides = (3,3)),
    SpatialDropout2D(0.2),
    BatchNormalization(),
    MaxPooling(pool_size=(2,2), strides = (2,2)),


    Conv2D(filters = 128, padding="zero", strides = (3,3)),
    SpatialDropout2D(0.2),
    BatchNormalization(),
    MaxPooling(pool_size=(2,2), strides = (2,2)),


    Conv2D(filters = 256, padding="zero", strides = (3,3)),
    SpatialDropout2D(0.2),
    BatchNormalization(),
    MaxPooling(pool_size=(2,2), strides = (2,2)),


    Conv2D(filters = 512, padding="zero", strides = (3,3)),
    SpatialDropout2D(0.2),
    BatchNormalization(),
    MaxPooling(pool_size=(2,2), strides = (2,2)),


    Conv2D(filters = 1024, padding="zero", strides = (3,3)),
    SpatialDropout2D(0.2),
    BatchNormalization(),
    MaxPooling(pool_size=(2,2), strides = (2,2)),


    layers.Flatten(),
    Dense(units=2048),
    BatchNormalization(),

    Dense(units=1, activation = "sigmoid"),
])


model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [ ]:
patience = 5

cb = keras.callbacks.EarlyStopping(
    monitor='val_loss', min_delta=0, patience=patience, verbose=0, mode='auto',
    baseline=None, restore_best_weights=False
)
model.save('test.h5')
model.save_weights('zero.h5')
history = model.fit(train_generator,
                  epochs=1000, #we stop training the model with early stopping
                  validation_data=val_generator,
                  callbacks=[cb]
                  )

model.save(save.h5)
model.save_weights('model_first.h5')

#retrain on the whole dataset for the same epochs as before
model.load_weights('def.h5')
epochs = (len (history.history['loss']) - patience)

history = model.fit(all_generator,
                  epochs = epochs)


model.save_weights('model_w.h5')
model.save('model.h5')

Epoch 1/1000
67/67 [==============================] - 542s 8s/step - loss: 4.1220 - accuracy: 0.5856 - val_loss: 8.9615 - val_accuracy: 0.5000
Epoch 2/1000
67/67 [==============================] - 43s 647ms/step - loss: 0.8376 - accuracy: 0.6897 - val_loss: 1.1200 - val_accuracy: 0.5000
Epoch 3/1000
67/67 [==============================] - 43s 646ms/step - loss: 0.7549 - accuracy: 0.7176 - val_loss: 0.9076 - val_accuracy: 0.5000
Epoch 4/1000
67/67 [==============================] - 43s 647ms/step - loss: 0.5554 - accuracy: 0.7576 - val_loss: 0.6529 - val_accuracy: 0.8253
Epoch 5/1000
67/67 [==============================] - 43s 647ms/step - loss: 0.5442 - accuracy: 0.7838 - val_loss: 1.0130 - val_accuracy: 0.5019
Epoch 6/1000
67/67 [==============================] - 43s 646ms/step - loss: 0.5994 - accuracy: 0.7578 - val_loss: 0.9721 - val_accuracy: 0.5000
Epoch 7/1000
67/67 [==============================] - 43s 645ms/step - loss: 0.4925 - accuracy: 0.8056 - val_loss: 1.9474 - val_accu

In [115]:
model = keras.models.load_model('test.h5')

# Task 3 - Evaluation

In [56]:
# Display how many test data respect to normal and pneumonia
test_dir = 'drive/MyDrive/lung/encoded'

test_normal_dir = os.path.join(test_dir, 'NORMAL')
test_pneumonia_dir = os.path.join(test_dir, 'PNEUMONIA')

print('total test normal images:', len(os.listdir(test_normal_dir)))
print('total test pneumonia images:', len(os.listdir(test_pneumonia_dir)))

total test normal images: 30
total test pneumonia images: 21


In [57]:
# Read the test text file and store into list
# And split into x_test and y_test for labels
test_dir = 'drive/MyDrive/lung/encoded'
labels = []
texts = []
for label_type in ['NORMAL', 'PNEUMONIA']:    
    dir_name = os.path.join(test_dir, label_type)
    for fname in os.listdir(dir_name):
        if fname[-4:] == '.txt':
            f = open(os.path.join(dir_name, fname))
            tex = []
            for line in f:
                row = line.split()
                for r in row:
                    r1 = float(r)  # Convert string to float
                    tex.append(r1) # (50176)
                                               
            texts.append(tex)      # (51*50176)
            if label_type == 'NORMAL':
                labels.append(0)   # Labled Normal to 0     
            else:
                labels.append(1)   # Labled PNEUMONIA to 1         

In [58]:
# Convert list to np array in order to reshape
x_test=np.array(texts)
y_test=np.array(labels)
print(x_test.shape)

# Reshape as the same format as train
x_test=x_test.reshape(51,224,224,1) 
print(x_test.shape)

(51, 50176)
(51, 224, 224, 1)


In [210]:
# Parameters
params = {'dim': (224,224),
          'batch_size': 32,
          'n_classes': 2,
          'n_channels': 1,
          'shuffle': True}

# Datasets
partition = partition   # path as IDs
labels = lables         # Labels

# Call DataGenerator function from custom class 
eval_generator = DataGenerator(x_test, y_test, **params)
#all_generator = DataGenerator(partition['all'], labels, **params)

In [211]:
#model_2.load_weights('model.h5')
# Choose one of them
##test_loss, test_acc =model_2.evaluate(x_test, y_test, steps=1)

#print('test acc:', test_acc)
model.evaluate(test_generator)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py:583: RuntimeWarning: divide by zero encountered in log10
  numdigits = int(np.log10(self.target)) + 1


OverflowError: ignored